version: "3.8"
services:
  unftp:
    image: bolcom/unftp:v0.14.7-9-g83696d1-alpine
    restart: always
    ports:
      - "30000:30000"
      - "2121:2121"
      - "50000:50000"
      - "50001:50001"
      - "50002:50002"
      - "50003:50003"
      - "50004:50004"
      - "50005:50005"
      - "8080:8080"
    env_file:
      - ./env.docker-compose
    depends_on:
      - azurite
    volumes:
      - ./ftp:/ftp
  azurite:
    ports:
      - "10000:10000"
    expose:
      - "10000"
      - "10001"
      - "10002"
    image: mcr.microsoft.com/azure-storage/azurite
    volumes:
      - ./data:/data
